name: Build YTLitePlus

on:
  workflow_dispatch:
    inputs:
      decrypted_youtube_url:
        description: "The *decrypted* YouTube ipa (Provide Direct Download Link)."
        default: ""
        required: true
        type: string
      ytliteplus_version:
        description: "The version of YTLitePlus to inject (Provide *FULL* SHA, Tag, or Branch)."
        default: "main"
        required: true
        type: string

jobs:
  build:
    name: Build YTLitePlus
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6
        with:
          repository: YTLitePlus/YTLitePlus
          ref: ${{ inputs.ytliteplus_version }}
          path: main
          submodules: recursive

      - name: Prepare YouTube IPA
        run: |
          wget "${{ inputs.decrypted_youtube_url }}" --no-verbose -O main/YouTube.ipa
          unzip -q main/YouTube.ipa -d main/tmp
          echo "YT_VERSION=$(grep -A 1 '<key>CFBundleVersion</key>' main/tmp/Payload/YouTube.app/Info.plist | grep '<string>' | awk -F'[><]' '{print $3}')" >> $GITHUB_ENV
          wget -qO- https://github.com/dayanch96/YTLite/releases/latest > main/tmp/release_page.html
          YTLITE_VERSION=$(grep -o -E '/tag/v[^"]+' main/tmp/release_page.html | head -n 1 | sed 's/\/tag\/v//')
          echo "YTLITE_VERSION=${YTLITE_VERSION}" >> $GITHUB_ENV
          echo $YTLITE_VERSION
          rm -rf main/tmp/Payload/YouTube.app/_CodeSignature/CodeResources
          rm -rf main/tmp/Payload/YouTube.app/PlugIns/*
          cp -R main/Extensions/*.appex main/tmp/Payload/YouTube.app/PlugIns
    
      - name: Install Dependencies
        run: brew install ldid make

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Restore cache if available
        id: cache
        uses: actions/cache/restore@v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: Setup Theos
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.6
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Setup iOS SDK
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.6
        with:
          repository: theos/sdks
          path: theos/sdks
          sparse-checkout: "iPhoneOS16.5.sdk"
          sparse-checkout-cone-mode: false

      - name: Save cache if available
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.6
        with:
          repository: qnblackcat/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        working-directory: ${{ github.workspace }}/theos-jailed
        run: |
          ./install

      - name: Fix Compilation & Build IPA
        working-directory: ${{ github.workspace }}/main
        run: |
          sed -i '' "s/^PACKAGE_VERSION.*$/PACKAGE_VERSION = ${{ env.YT_VERSION }}-${{ env.YTLITE_VERSION }}/" Makefile

          sed -i '' "1s#.*#TARGET = iphone:clang:16.5:14.0#g" Makefile

          sed -i '' "3s#.*#export TARGET = iphone:clang:16.5:15.0#g" Tweaks/Alderis/Makefile
          sed -i '' "5s#.*#export TARGET = iphone:clang:16.5:12.0#g" Tweaks/Alderis/Makefile
          sed -i '' "7s#.*#export TARGET = iphone:clang:16.5:12.0#g" Tweaks/Alderis/Makefile
          
          gmake package FINALPACKAGE=1

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: (v${{ env.YT_VERSION }})-(${{ env.YTLITE_VERSION }})-(${{ github.run_number }})
          name: (v${{ env.YT_VERSION }})-(${{ env.YTLITE_VERSION }})-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: true
